### ISSUE TITLE
Literal out of range errors from overflowing_literals lint

### ISSUE THREAD

**Issue by ollie27** [ishanjain28/pulseaudio-dlna#1]
In a future version of Rust the `overflowing_literals` lint will become deny by default. See rust-lang/rust#55632. When checking for breakage in crates uploaded to crates.io it was discovered that this crate will no longer compile thanks to this lint. The error produced is [here](https://crater-reports.s3.amazonaws.com/pr-55632/try%23dc13be39fae8d4c607889b27de374b52586485a3/gh/ishanjain28.pulseaudio-dlna/log.txt).

**Comment by ishanjain28** [comment]
@ollie27 Hi there, Thank you so much for bringing this to my attention. This tool was supposed to be a CLI tool and I was not going to put it on crates.io. 

I encountered some difficulties with libdbus and I just don't even know if I am going to complete this anymore.

**Comment by ishanjain28** [comment]
@ollie27 I checked the linked issue, Please go ahead. I'll probably scrap this project or maybe go ahead and complete it.
